on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "2f98ae04-67ab-48e7-9634-ab6e9d70d70b",
              "clientSecret": "-1c8Q~XU4VjjjIQ-k38z4~xHPVlOJpR_uU-MLcqZ",
              "subscriptionId": "61fd4d7d-742d-4d50-b08e-7809b23001a1",
              "tenantId": "84ce4985-6ead-44e3-8708-7f892d770fdd"
            }

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.6"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
